version: '3'

services:
    node:
        build: .
        links:
            - redis
        ports:
            - "8080:8080"
        volumes:
            - ./:/src
        env_file: ~/status-check.env

    redis:
        image: redis
        ports:
<<<<<<< HEAD
            - "6379"
    
=======
            - "6379"
>>>>>>> bbe0a1951f3e3cab18f488aec40d5231fbe4279e
